# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created: Sat May  7 15:29:39 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 614)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/mainWindow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.video_fr = QtWidgets.QFrame(self.layoutWidget)
        self.video_fr.setMinimumSize(QtCore.QSize(500, 0))
        self.video_fr.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.video_fr.setAutoFillBackground(True)
        self.video_fr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_fr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_fr.setObjectName("video_fr")
        self.verticalLayout.addWidget(self.video_fr)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.progressSlider_hs = QtWidgets.QSlider(self.layoutWidget)
        self.progressSlider_hs.setOrientation(QtCore.Qt.Horizontal)
        self.progressSlider_hs.setObjectName("progressSlider_hs")
        self.horizontalLayout.addWidget(self.progressSlider_hs)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PlayPause_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.PlayPause_btn.setMaximumSize(QtCore.QSize(35, 35))
        self.PlayPause_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayPause_btn.setIcon(icon1)
        self.PlayPause_btn.setAutoRepeat(True)
        self.PlayPause_btn.setFlat(True)
        self.PlayPause_btn.setObjectName("PlayPause_btn")
        self.horizontalLayout_2.addWidget(self.PlayPause_btn)
        self.Stop_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Stop_btn.setMaximumSize(QtCore.QSize(35, 35))
        self.Stop_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Stop_btn.setIcon(icon2)
        self.Stop_btn.setAutoRepeat(True)
        self.Stop_btn.setFlat(True)
        self.Stop_btn.setObjectName("Stop_btn")
        self.horizontalLayout_2.addWidget(self.Stop_btn)
        self.volume_label = QtWidgets.QLabel(self.layoutWidget)
        self.volume_label.setMaximumSize(QtCore.QSize(25, 20))
        self.volume_label.setText("")
        self.volume_label.setPixmap(QtGui.QPixmap(":/icons/icons/volume_50.png"))
        self.volume_label.setScaledContents(True)
        self.volume_label.setObjectName("volume_label")
        self.horizontalLayout_2.addWidget(self.volume_label)
        self.volumeSlider_hs = QtWidgets.QSlider(self.layoutWidget)
        self.volumeSlider_hs.setMinimumSize(QtCore.QSize(100, 0))
        self.volumeSlider_hs.setMaximumSize(QtCore.QSize(100, 16777215))
        self.volumeSlider_hs.setMaximum(100)
        self.volumeSlider_hs.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider_hs.setObjectName("volumeSlider_hs")
        self.horizontalLayout_2.addWidget(self.volumeSlider_hs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.quality_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.quality_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.quality_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.quality_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/quality.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/quality_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quality_btn.setIcon(icon3)
        self.quality_btn.setCheckable(False)
        self.quality_btn.setChecked(False)
        self.quality_btn.setAutoRepeat(False)
        self.quality_btn.setAutoExclusive(False)
        self.quality_btn.setFlat(True)
        self.quality_btn.setObjectName("quality_btn")
        self.horizontalLayout_2.addWidget(self.quality_btn)
        self.quality_cb = QtWidgets.QComboBox(self.layoutWidget)
        self.quality_cb.setMaximumSize(QtCore.QSize(16777215, 25))
        self.quality_cb.setFrame(True)
        self.quality_cb.setObjectName("quality_cb")
        self.quality_cb.addItem("")
        self.quality_cb.addItem("")
        self.quality_cb.addItem("")
        self.quality_cb.addItem("")
        self.quality_cb.addItem("")
        self.quality_cb.addItem("")
        self.horizontalLayout_2.addWidget(self.quality_cb)
        self.Twitch_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.Twitch_btn.setEnabled(True)
        self.Twitch_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Twitch_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/twitch_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Twitch_btn.setIcon(icon4)
        self.Twitch_btn.setFlat(True)
        self.Twitch_btn.setObjectName("Twitch_btn")
        self.horizontalLayout_2.addWidget(self.Twitch_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chatBar_tabWidget = QtWidgets.QTabWidget(self.layoutWidget1)
        self.chatBar_tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.chatBar_tabWidget.setObjectName("chatBar_tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chat_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.chat_textBrowser.setEnabled(True)
        self.chat_textBrowser.setMinimumSize(QtCore.QSize(300, 0))
        self.chat_textBrowser.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.chat_textBrowser.setFont(font)
        self.chat_textBrowser.setOverwriteMode(True)
        self.chat_textBrowser.setObjectName("chat_textBrowser")
        self.verticalLayout_3.addWidget(self.chat_textBrowser)
        self.message_textEdit = QtWidgets.QTextEdit(self.tab)
        self.message_textEdit.setEnabled(True)
        self.message_textEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.message_textEdit.setMaximumSize(QtCore.QSize(600, 60))
        self.message_textEdit.setObjectName("message_textEdit")
        self.verticalLayout_3.addWidget(self.message_textEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.send_btn = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.send_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_btn.setIcon(icon5)
        self.send_btn.setCheckable(False)
        self.send_btn.setAutoRepeat(True)
        self.send_btn.setFlat(True)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_3.addWidget(self.send_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatBar_tabWidget.addTab(self.tab, icon6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.banner_channel_lb = QtWidgets.QLabel(self.tab_2)
        self.banner_channel_lb.setMinimumSize(QtCore.QSize(300, 300))
        self.banner_channel_lb.setMaximumSize(QtCore.QSize(300, 300))
        self.banner_channel_lb.setText("")
        self.banner_channel_lb.setObjectName("banner_channel_lb")
        self.verticalLayout_5.addWidget(self.banner_channel_lb)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.game_channel_lb = QtWidgets.QLabel(self.tab_2)
        self.game_channel_lb.setText("")
        self.game_channel_lb.setObjectName("game_channel_lb")
        self.horizontalLayout_4.addWidget(self.game_channel_lb)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.folowers_channel_lb = QtWidgets.QLabel(self.tab_2)
        self.folowers_channel_lb.setText("")
        self.folowers_channel_lb.setObjectName("folowers_channel_lb")
        self.horizontalLayout_5.addWidget(self.folowers_channel_lb)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.partner_channel_lb = QtWidgets.QLabel(self.tab_2)
        self.partner_channel_lb.setText("")
        self.partner_channel_lb.setObjectName("partner_channel_lb")
        self.horizontalLayout_6.addWidget(self.partner_channel_lb)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.views_channel_lb = QtWidgets.QLabel(self.tab_2)
        self.views_channel_lb.setText("")
        self.views_channel_lb.setObjectName("views_channel_lb")
        self.horizontalLayout_7.addWidget(self.views_channel_lb)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.language_channel_lb = QtWidgets.QLabel(self.tab_2)
        self.language_channel_lb.setText("")
        self.language_channel_lb.setObjectName("language_channel_lb")
        self.horizontalLayout_8.addWidget(self.language_channel_lb)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.love_btn = QtWidgets.QPushButton(self.tab_2)
        self.love_btn.setEnabled(True)
        self.love_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.love_btn.setMaximumSize(QtCore.QSize(60, 50))
        self.love_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.love_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/love_yes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.love_btn.setIcon(icon7)
        self.love_btn.setIconSize(QtCore.QSize(50, 50))
        self.love_btn.setFlat(True)
        self.love_btn.setObjectName("love_btn")
        self.verticalLayout_5.addWidget(self.love_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/channel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chatBar_tabWidget.addTab(self.tab_2, icon8, "")
        self.verticalLayout_2.addWidget(self.chatBar_tabWidget)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 27))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menu)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_3.setIcon(icon9)
        self.menu_3.setObjectName("menu_3")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFile.setIcon(icon10)
        self.actionFile.setObjectName("actionFile")
        self.actionUrl = QtWidgets.QAction(MainWindow)
        self.actionUrl.setObjectName("actionUrl")
        self.actionStream = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/stream.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStream.setIcon(icon11)
        self.actionStream.setObjectName("actionStream")
        self.exit_action = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_action.setIcon(icon12)
        self.exit_action.setObjectName("exit_action")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon13)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon14)
        self.actionAbout.setObjectName("actionAbout")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionMesError = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMesError.setIcon(icon15)
        self.actionMesError.setObjectName("actionMesError")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon16)
        self.actionSettings.setObjectName("actionSettings")
        self.actionFavorit = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/favorite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFavorit.setIcon(icon17)
        self.actionFavorit.setObjectName("actionFavorit")
        self.menu_3.addAction(self.actionFile)
        self.menu_3.addAction(self.actionStream)
        self.menu.addAction(self.menu_3.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.exit_action)
        self.menu_2.addAction(self.actionHelp)
        self.menu_2.addAction(self.actionMesError)
        self.menu_2.addAction(self.actionAbout)
        self.menu_4.addAction(self.actionSettings)
        self.menu_4.addAction(self.actionFavorit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.chatBar_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Streamer v.1.0"))
        self.label.setText(_translate("MainWindow", "Время"))
        self.quality_cb.setItemText(0, _translate("MainWindow", "Source"))
        self.quality_cb.setItemText(1, _translate("MainWindow", "High"))
        self.quality_cb.setItemText(2, _translate("MainWindow", "Medium"))
        self.quality_cb.setItemText(3, _translate("MainWindow", "Low"))
        self.quality_cb.setItemText(4, _translate("MainWindow", "Mobile"))
        self.quality_cb.setItemText(5, _translate("MainWindow", "Audio"))
        self.chatBar_tabWidget.setTabText(self.chatBar_tabWidget.indexOf(self.tab), _translate("MainWindow", "Чат"))
        self.label_4.setText(_translate("MainWindow", "Игра:"))
        self.label_6.setText(_translate("MainWindow", "Подписчиков:"))
        self.label_7.setText(_translate("MainWindow", "Партнерка:"))
        self.label_8.setText(_translate("MainWindow", "Просмотров:"))
        self.label_9.setText(_translate("MainWindow", "Язык:"))
        self.chatBar_tabWidget.setTabText(self.chatBar_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "О канале"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_3.setTitle(_translate("MainWindow", "Открыть"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.menu_4.setTitle(_translate("MainWindow", "Настройка"))
        self.actionFile.setText(_translate("MainWindow", "Файл"))
        self.actionUrl.setText(_translate("MainWindow", "Url"))
        self.actionStream.setText(_translate("MainWindow", "Стрим"))
        self.exit_action.setText(_translate("MainWindow", "Выход"))
        self.actionHelp.setText(_translate("MainWindow", "Справка"))
        self.actionAbout.setText(_translate("MainWindow", "О программе"))
        self.action.setText(_translate("MainWindow", "Отправить сообщение об ошибке"))
        self.actionMesError.setText(_translate("MainWindow", "Сообщить о ошибке"))
        self.actionSettings.setText(_translate("MainWindow", "Параметры"))
        self.actionFavorit.setText(_translate("MainWindow", "Избранные каналы"))

import res_rc
